import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/component/sidebar";
import TopBar from "@/components/component/TopBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopBar />
        <div className="flex">
          <Sidebar />
        {children}
        </div>
        </body>
    </html>
  );
}
